src/components/Header/MobileOptions.tsx
src/components/Header/index.tsx
src/pages/Pool/index.tsx

While waiting for the next DXstats release, that will introduce multi-chain data, I've updated the current DXstats links to include the targeted chain id. Once DXstats will be released, Swapr will tie in seamlessly.

Multi-chain DXstats links

---

src/components/NetworkSwitcherPopover/index.tsx
src/components/WalletModal/PendingView.tsx
src/connectors/CustomWalletConnectConnector.ts
src/connectors/index.ts

Makes WalletConnect's targeted chain, and user-selected chain from network switcher in sync. I.e. if a user selects xDai from the network switcher, and later initiates a WalletConnect connection, the connection will refer to xDai.

WalletConnect targeted chain chainge

---

package.json
src/components/Settings/index.tsx
src/components/Web3Status/AccountStatus.tsx
src/components/Web3Status/index.tsx
src/hooks/useENSAvatar.ts
yarn.lock

Adds `useENSAvatar` hook which retrieves the current EOA avatar from the ENS Metadata API. Feel free to suggest a better way. 
- Closes #481 
Haven't tested the mobile view.
You need a wallet with ENS avatar, the best way I found is to impersonate a wallet using [Impersonator](https://apoorvlathey.com/impersonator/) and WalletConnect.
ENS Wallets with avatars:
- nick.eth, works on 1inch and Swapr but not Uniswap.
- brantly.eth, has the avatar but doesn't work 1inch Swapr nor Uniswap.
More ENS names from https://twitter.com/BrantlyMillegan/status/1456640949052973065

Feature - ENS Avatar support

---

src/hooks/useAllPairs.ts

- Issue was that there was limit of 100 pairs to be fetched and it was omitting 70 pairs from search on xDai
- added 1000 pairs limit
closes #586

Fix certain pairs not showing

---

src/hooks/useAllLiquidtyMiningCampaigns.ts

A regression was introduced in Beta 10 where the query to The Graph is only fetching the first 100 campaigns (by default). Increasing the limit to 999 as **a quick fix, for now,** fixes this.

fix: some liquidity mining campaigns are not showing

---

package.json
src/hooks/useLiquidityMiningCampaignPosition.ts
yarn.lock

An inconsistency was present between shown claimable/claimed tokens in multi-reward campaigns and the actual onchain data.
The inconsistency stems from the fact that rewards as indexed on the subgraph were used to determine which token amount was claimable/claimed. The claimable/claimed amounts were coming directly from the onchain state, and there was no guarantee that the order of the rewards was the same between the onchain distribution contract and the subgraph.
The fix consists in fetching the reward tokens (the addresses) exactly ordered as they are onchain and using those ordered addresses to get the token related to the claimed/claimable amounts.

Fix multi rewards campaigns claimable and claimed token amounts

---

src/components/Pool/PairsList/CampaignCard/index.tsx

Fixes #742
Make the campaign card content to fit the available space.
before:
after:
before:
after:
1. Open the page `Rewards`

fix: add flex layer and grow

---

src/components/Header/index.tsx
src/components/Header/swpr-info/index.tsx

Fixes #744 
Add right spacing for skeleton components inside the `Header` component.
before:
after:
1. Reload the page

fix: add loading balances spacing

---

public/locales/en.json
src/hooks/useWrapCallback.ts

Fixes #720
Fix button message when wrapping but there is enough ETH/WETH balance
1. Open Swap page
2. Choose to wrap ETH to WETH with enough balance
2. Choose to unwrap WETH to ETH with enough balance

[Fix] Fix button message when wrapping

---

src/components/Header/index.tsx

I adjusted the media query as well since it was overlapping when it gets close to medium size..

Added Stats to the Navigation

---

src/pages/App.tsx
src/theme/index.tsx

Fixes #738 
Fix body margin added by react-remove-scroll-bar lib.
https://user-images.githubusercontent.com/23079677/158165532-d8521cee-fb0c-4c61-be3b-aaf9a9a1cb18.mp4
1. Open any modal
Found this as the only solution for the css that react-remove-scroll-bar is injecting with `!impotatnt` property. The only other solution I found is to use a better modal lib that has a good scrolling prevention solution.

[Fix] Fix horizontal page jump

---

src/components/TransactionSettings/index.tsx

Fixes #776 
Added slippage tolerance validation for negative values.
Prevent deadline overflow bug.
1. Open the setting popup

Fix slippage tolerance & deadline validation

---

src/components/Badge/Carrot/index.tsx
src/components/Pool/PairsList/Pair/index.tsx

Fixes #745 
Add a transparent border for state badges on `greyed` state.
Also remove the left margin for the farming badge, since it's missing in figma.
1. Open the page `Liquidity`

fix: add transparent border

---

src/components/Header/index.tsx

Closes #818 
Previously when selected Gnosis chain on top was black bar. 
1. Open the `Swapr`

fix black bar on gnosis

---

src/components/Header/index.tsx
src/hooks/useGasInfo.ts

Fixes #812 
Show account balance only when user's wallet is connected. The same as gas on Gnosis Chain.
1. Open the swapr app
2. Switch network to Gnosis Chain
3. Connect wallet to any network
4. Connect wallet to Gnosis Chain

Show eth balance only when wallet connected

---

public/locales/en.json
src/components/CurrencyInputPanel/index.tsx
src/components/FiatValueDetails/index.tsx
src/components/RecipientField/index.tsx
src/components/swap/AdvancedSwapDetailsDropdown.tsx
src/components/swap/SwapPlatformSelector.tsx
src/components/swap/SwapSettings.tsx
src/components/swap/TradePrice.tsx
src/components/swap/styleds.tsx
src/pages/Swap/index.tsx
src/theme/landingPageTheme/global.css
src/utils/prices.ts

- Fix css for better screen space usage
- Trim numbers to prevent overflows
- Fix add recipient UX
- Remove priceImpact and move it to exchanges table
Closes #811
- Enhance user and mobile experience in new Swapbox, more responsive Swapbox
- Fix Recipient input UX
- Remove bottom price impact and add it to exchanges list.
1. Open the `swap` page in mobile view
2. Click in the Add Recipient icon
2. Simulate trade

[Fix] Enhance user and mobile experience in new Swapbox

---

public/locales/en.json
src/components/swap/SwapPlatformSelector.tsx
src/components/swap/SwapRoute.tsx

Closes #643
Add EcoRouter platform list show more markets button.
2. Choose a trading pair with more than 3  available markets
3. Click in "Show more"

[Feature] EcoRouter show more markets button

---

src/components/Web3Status/AccountStatus.tsx

Closes #824
This PR fixes showing extra empty space on accounts with ENS without image attached.
**Current**
**Old**
1. Open swapr app

Fix showing avatar empty space on accounts with ENS but no image attached

---

src/components/Web3Status/index.tsx

Fixes #897 
Unsupported network popup should close after switch to supported via metamask
1. Open app and connect with MetaMask
2. Switch to unsupported network
3. Popup appears and asks for switching network 
4. Switch network **with MetaMask**
5. Popup should be closed after succesful connection with supported network

fix: hide unsupported net popup

---

src/components/SpaceBg/index.js
src/pages/Pools/index.tsx

_Me and @berteotti are working on updating the design of liquidity page and also the fonts and colors._
We will do this smaller PRs and merge it on a "main" branch -> `feature/fonts-and-colors-liquidity-page`.
--- 
Add space background image to liquidity
1. go to liquitidy page
- check there is the space background image

[liquidity redesign] Add space background image to liquidity page

---

src/pages/Swap/index.tsx
src/utils/maxAmountSpend.ts

Add max balance to output token when clicking on balance.
https://user-images.githubusercontent.com/23079677/163380387-1133127c-9c0b-449a-be26-e7fb0460f66b.mp4
1.  Open the page `swap`
2. Simulate trade
3. Click in output token max balance

[Feautre] Add max balance to output token

---

src/components/LandingPageComponents/Stats.js

Also imported API urls from `client.ts`
Fixes #795
Handle errors when fetching stats from subgraphs on the landing page.
**Now**
If there is an error fetching a subgraph we show "not updated" bellow stats.
**Previously** 
eg. when a subgraph was down the page broke and showed this error.
We can only test if it fails to fetch from subgraph.
1. Open landing page

[fix] Handle error when it fails to fetch a subgraph on landing page stats

---

src/theme/landingPageTheme/global.css

Remove white text color CSS which is overriding some text colors.

[Fix] Remove white text color CSS

---

src/pages/AddLiquidity/index.tsx
src/pages/RemoveLiquidity/index.tsx
src/state/application/actions.ts
src/state/application/hooks.tsx
src/state/application/reducer.test.ts

Fixes #872 
Fix connect wallet button not opening the wallet switcher modal.
**Now**
1. Open the page `liquidity` with wallet not connected

Fix connect wallet button not opening the wallet switcher modal

---

.github/workflows/deploy-preview.yml

Fix IPFS deploy Github workflow with 
1. concurrency cancel if another build starts after this.
2. yarn cache
IPFS deploy action should pass and deploy to IPFS

Fix IPFS deploy Github workflow

---

src/pages/Bridge/index.tsx

Closes #871  
Add placeholder text on history tab

[Fix] ecoBridge - added placeholder text on history tab

---

src/pages/Bridge/BridgeTransactionsSummary.tsx
src/pages/Bridge/index.tsx

Closes #930 
Added margin to bridge transactions summary
Before
After

[Fix] add margin to bridge txs history

---

src/theme/index.tsx

Fixed font size on WalletConnect modal 
1. Open the `Swapr`

[FIX] walletconnect font size

---

src/components/CurrencyInputPanel/CurrencyInputPanel.container.tsx
src/services/EcoBridge/Arbitrum/ArbitrumBridge.selectors.ts
src/services/EcoBridge/Socket/Socket.selectors.ts
src/utils/index.test.ts
src/utils/index.ts

Closes #913 
Fixed parsing transaction value.
`0000.000002` to `0.000002`
`.000002` to `0.000002`
`0000.00002` 
`.00002`
`00221`

[FIX ] eco bridge fix parsing value

---

src/hooks/useAllLiquidtyMiningCampaigns.ts

DerivedCurrency for singleStaked campaigns are getting zero and triggering a fraction result to infinity
Fixes #963
Now put toSingleSidedStakeCampaign in try catch and skip those campaigns with `campaign.stakeToken.derivedNativeCurrency` is `0`
Go to swapr in rinkeby network and go to rewards page.

Fix for rewards crash

---

src/components/LandingPageComponents/layout/Hero.js

Fixes #961 
Marque was throwing unique key error in developer mode. 
Run app in local and open developer view of browser and check console. Unique key error from Hero.js should not appear
```react-fast-marquee``` was duplicating elements and inside array mapping proper keys for elements was not provided.

Added unique keys to array map of elements

---

src/components/Header/index.tsx

Fixes #983
Even when not connected the gas and default token was taking space since it was `visibility: hidden` in css so the total height of the Top menu was 100px and when switch to polygon this default token was empty and the Top menu will shrink to 84px. 
Solution: Made the top bar height to 100px always.
#983 should pass.

[#983] Bug-fix background image move on polygon

---

src/pages/Pools/LiquidityMiningCampaign/index.tsx

Fixes #869 
-button for single sided rewards used to always say get swapr now it will say token name that campaign is related to
1. Go to gnosis chain
2. go to this curv expired single sided campaign http://localhost:3000/#/rewards/single-sided-campaign/0x712b3d230F3C1c19db860d80619288b1F0BDd0Bd/0x7AbD8D2990Ac41031D968093BFEC742b35E7fdF3?chainId=100 and check that swapr single sided campaings are showing proper text as well
4. should show curve

Single sided campaign dynamic token name for get button

---

src/services/EcoBridge/EcoBridge.config.ts
src/state/index.ts

Fixes #1012
During development interface of `arbitrumBridge` transactions has been changed few times to end up with `entityAdapter`. If user had interacted with interfaces used meanwhile they have been persisted in `localStorage` by `redux-localstorage-simple` lib. Due to how it works, it loaded persisted incompatible state from `localStorage` (ignoring new initial store interface). Redux then interacted with stale state throwing errors.
This fix basically checks for presence of persisted keys and checks if it's compatible with `entityAdapter`, if not - entry is cleared and `redux` recreates store with correct interface. It's lightweight and takes around 0.3 ms to execute regardless of transactions length.
1. Recreate a bug with steps provided in #1012
2. In console you should see warning …

fix(ecoBridge): clear legacy txs interface to preserve compatibility

---

src/utils/prices.ts

Fixes #918
Fix DECIMALS error showing up when trading ZEENUS, as this currency has 0 decimals.
2. Choose ZEENUS for swapping

fix: fix decimals error when swapping

---

src/lib/eco-router/api.ts
src/lib/eco-router/platforms.ts

Quick fix for Polygon network. :) 
1. Open the dapp.
2. Select Polygon.
3. Select trading pairs and amounts
4. Eco Router should show either DYFN, Sushi, or QuickSwap.
The SDK is missing the default fallback RPC provider entry for Polygon. If no provider is passed, the `JsonRpcProvider` from ethers defaults to `localhost: 8545` of ganache.

bugfix: Eco Router returns no results on Polygon 

---

src/components/SearchModal/CurrencySearchModal/CurrencySearchModal.component.tsx
src/components/SearchModal/CurrencySearchModal/CurrencySearchModal.container.tsx

Fixes this weird error that appeared after #1056 when running `yarn start`

fix: ReferenceError: Cannot access 'x' before initialization

---

package.json
src/lib/eco-router/api.ts
yarn.lock

Updates Swapr SDK to v1.4 to use updated `getAllCommonUniswapV2Pairs` (less RPC calls using multicall2 for `getReserves` and `swapFee` on Swapr pairs) and `getAllCommonUniswapV2PairsFromSubgraph` which fetches the common pairs from the subgraph. This provides a better route efficiency by including all available pairs. 
This PR also fixes the execution price display bug found by @0xVenky.

feature: update Swapr SDK to v1.4 beta

---

src/components/SearchModal/CurrencySearch/CurrencySearch.component.tsx

Closes #951 
Native currency is now included in search results on similar rules as regular token (not only when query is beginning of native currency symbol).
To test:
1. Open token search in any place (swap/bridge) on any chain (examples are on mainnet as symbol is different than name (ETH, Ether)
2. Following queries should include ETH on token list (should work even when query starts with spaces):
- eth
- er
- the
- ...etc

make full text search on native currency name & symbol

---

package.json
src/components/SearchModal/utils/filtering.ts
src/state/multicall/updater.tsx
src/utils/retry.ts
tsconfig.json
yarn.lock

Currently `typecheck` fails on `Connext Bridge` because the version of typescript is too low (`from: ^3.8.3` to: `^4.7.3`)
```ts
if (searchingAddress) {
const lower = searchingAddress.toLowerCase()
return (t: T | Currency) => 'address' in t && lower === t.address?.toLowerCase()
}
```

Upgrade tsc version

---

.lintstagedrc

There is no need for running precommit lint check for tests files - it fail as in some of those files there are hard coded awaits which are impossible to avoid due to Synpress bug

Fix for precommit lint check for tests files

---

.github/workflows/auto-rebase-dependabot.yml

Dependabot PR's base may not be updated to the latest and can create conflicts. So creating a CI workflow to auto rebase it once dependabot creates a PR.
Once dependabot creates a new PR it will be rebased to the latest

Auto rebase dependabot PR's

---

src/components/SearchModal/CurrencySearch/CurrencySearch.component.tsx

Fix #1134
Previously user could select native currency when trying bridge from `testnet` to `realnet`
1. Go to page `Bridge`
2. Set `fromChain` to 'Rinkeby' or `A. Rinkeby`
3. Set `toChain` to realnet (eg `Ethereum`, `Gnosis`)
4. Open token list
5. There shouldn't be any token

disable native currency when trying bridge from testnet to realnet

---

.vscode/settings.json
package.json

Removed line in vscode to show printWidth
Removed unwanted @types/qs dependency since we are no longer using qs library

Removed unwanted type package and .vscode printWidth fix

---

src/components/swap/SwapButtons/SwapButton.tsx
src/components/swap/SwapButtons/SwapButtons.tsx
src/constants/index.tsx
src/state/swap/hooks.ts

Fixes #1188
Show is loading state when wallet is disconnected. Also improved how we handle swap input errors.
2. Simulate a trade without connecting wallet

fix: show is loading state when wallet is disconnected

---

src/pages/Swap/index.tsx

No ticket.
Fixes a bug identified by Kacper when we try to wrap ETH on Rinkeby.
On the swap page
Using the Rinkeby Chain
Select ETH and WETH as input and output Currencies. Add a value
Verify WRAP is available and functional
The origin of the problem was a change made when implementing the COW trade.

Fix typedValue when calling wrapCallback

---

public/locales/en.json
src/components/CurrencyInputPanel/CurrencyInputPanel.component.tsx
src/components/CurrencyInputPanel/CurrencyInputPanel.styles.ts
src/components/CurrencyInputPanel/CurrencyUserBalance.tsx

Fixes #1180
Shou balance on currency input outside swapbox
1. Open any `reward campaign` page where you have LP
2. Click Deposit Stake or any other option related to stake / unstake

fix: show balance on currency input

---

src/components/LandingPageComponents/layout/Hero.js

Fixes #1202
* Add negative margin for routing through the bar to level padding
Old:
New:
1. Open the main page
2. Check ROUTING THROUGH bar if margins are ok. Good to check on a bigger screen and different background then black

fix / add negative margin for routing through bar to level padding

---

src/components/Pool/PairView/UserLiquidity/UserLiquidity.tsx

fixes #1228 
increase poolTokenPercentage shown on user liquidity to 5 decimals
1.  Go to liquidity
2. Check 5 decimals on pool share

increase poolTokenPercentage shown on user liquidity to 5 decimals

---

src/pages/LiquidityMining/Create/index.tsx

Fixes #1095 
Remove curly brace `{` from toast message for creating campaign

Remove extra curly brace in toast message when creating campaign

---

src/components/Web3Status/AccountStatus.tsx

Fixes #1231
1. Open the `Swapr`

remove network name in network switcher

---

src/services/EcoBridge/Socket/api/index.ts

closes #1140 
Socket has migrated it's API domain to `api.socket.tech`. The previous domain `backend.movr.network` will be deprecated going forward. 
Check [Socket docs](https://docs.socket.tech/socket-api/versioning)
1. Open bridge page

Update socket domain. Previous domain will be deprecated 

---

src/components/swap/SwapButtons/SwapButton.tsx
src/theme/index.tsx

fixes #1191 
fix split "finding best price" to be responsive in smaller screens.
**previously**
**Currently on mobile**
**Currently on desktop**
1. Make a swap on mobile

Improve swap platforms rotating logo loading button to be responsive

---

.github/dependabot.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml

Only run nessasary CI for dependabot PR's
Once merge new Dependabot PR's should not run all the CI tests

Only run nessasary CI for dependabot PR's

---

config-overrides.js
package.json
yarn.lock

Add webpack bundle analyzer.
You need to add `.env.production.local` file with property `BUNDLE_ANALYZE=true` and then do `yarn build`
Then you should be able to see the above analyse page in http://127.0.0.1:8888/
To analyse which all packages contribute to the size of our bundles.

Add web-pack bundle analyser

---

src/components/TransactionSettings/index.tsx

Add `data-testid="slippage-error"` for slippage error message component.
1. Open transaction settings and set slippage tolerance value to show warning/error message box.

fix: add data-testid slippage-error

---

src/pages/Bridge/BridgeModal/BridgeModalContent.tsx

Fix backText button message
1. Go to bridge page and bridge asset

fix: bridge backText message key

---

src/components/swap/SwapButtons/SwapButton.tsx

Fixes #1344
Add spacing for the text in the swap button and set the smaller font to fit the mobile design
1. Go to the swap page
2. Select tokens on expert mode to have a high price impact
3. Check the design, also on mobile

Fix: 1344 add spacing for the text in swap button 

---

src/hooks/useUSDValue.ts
src/utils/coingecko.ts

Fixes #1283
Use Coingecko to fetch native currency prices
1. Simulate trade with native currency

fix: use native currency price

---

src/components/Header/index.tsx
src/components/SwaprVersionLogo/index.tsx

Fixes #1343 
Set for mobile smaller logo and bigger gap for the settings
1. Open any page where 'Expeditions' button is displayed
2. Check mobile design if button is not overlapping logo

Fix: 1343 set only on mobile smaller logo and bigger gap for settings

---

.github/workflows/ci.yml
tests/cypress/integration/smoke/MenuBarTests.ts
tests/synpress/specs/02transactionfull/bridge/BridgeTests.ts

This PR contains few improvements to the tests parts of CI pipe. It checks commit messages if they contain any flag that may change the way of starting tests:
*skip-cypress* - to skip cypress smoke tests 
*trigger-synpress* - to trigger run of synpress e2e tests
*trigger-synpress-dashboard* - to trigger run of synpress e2e tests with cypress dashboard reporter
Example: *git commit --allow-empty -m "skip-cypress" && git push* will trigger CI run without running any test
Also after the merge of this pr rerun of CI pipe should not cause fail of whole pipe

Improved getting commit messaged and fix for reruning tests

---

package.json
src/apollo/client.ts
src/components/NetworkSwitcher/NetworkSwitcher.preset.ts
src/components/Web3Status/AccountStatus.tsx
src/connectors/index.ts
src/constants/index.tsx
src/utils/chainSupportsSWPR.ts
yarn.lock

Adds support for Görli testnet and Swapr platform on the network. This config does not add support for DIY farming. We haven't deployed the staking contracts to Görli just yet. 
- User should be able to: 
- View and manage liquidity pairs.
- Retrieve data from the subgraph.
- Wrap ETH to WETH and trade using Swapr.
- Görli config does not break the dapp on the Bridge page.

feat: add Görli

---

src/services/EcoBridge/Connext/Connext.ts
src/services/EcoBridge/Connext/Connext.utils.ts

This PR introduces SilentLogger class that suppresses `print` method of default Logger used in connext sdk. Thanks to it browser's console is not spammed by undesired logs anymore. 
While working on different task I've noticed that console is spammed by logs from unknown origin: 
After brief investigation I found out that they were made by connext-sdk. There is no way to disable these logs in sdk config so I wrote implementation that suppresses `print` method in Logger and it's children instances. All other logs like errors and warnings will work as expected.
If you find these logs useful please disregard & close this PR.

feature(connext-bridge): suppress logs from sdk

---

src/state/swap/hooks.ts

- This is a quick fix but the issue is with the asynchronous function inside the useEffect hook called getTrades Im not sure yet how to approach it but we need refactor of this useDerivedSwapInfo hook. I think we should start off by moving the async function out of the useEffect and making a hook just for it.
closes #1350

Doesn't show routes when input is not selected

---

src/state/swap/hooks.ts

~~Adds `http` protocol to `StaticJsonRpcProvider` instance.~~ Removes static provider condition.

bugfix: remove static provider in eco router

---

.github/workflows/ci.yml

As we already used 3/4 of test results capacity i changed a bit the way of executing tests, right now, unless there is no label 'ready-for-tests' label on pr the cypress smoke tests will not be executed.
This is temporary solution as i am researching possibility to switch to sorry-cypress

Added check if pr got 'ready-for-tests' label to save test results capacity

---

src/connectors/CustomWalletConnectConnector.ts
src/connectors/index.ts
src/hooks/useNetworkSwitch.ts

Fixes #940 
WalletConnect wallets were not connecting properly nor were they changing `chainId`s properly. Although the issue raised was with Arbitrum One, this PR seeks to address it for all chains.
1. Disconnect your wallet.
2. If needed, clear application data in development tools and stop Metamask from automatically connecting.
3. Connect your WalletConnect based wallet (I used Trust Wallet)
4. Change networks
5. I haven't tested this but... To confirm everything works, test a functionality. I suggest doing a swap in a low fee chain.

Fix networks not working with WalletConnect

---

src/components/CurrencyInputPanel/CurrencyUserBalance.tsx

Fixes #1031
Fix incorrect rounded value of tokens when balance is too large
2. Choose a token with large balance

fix: incorrect rounded value of tokens in balance

---

src/pages/AddLiquidity/index.tsx

Fixes #1323
1. Open the page `liquidity`
2. Input token amount
3. Go to another page
4. Reopen `liquidity` page

fix: cleanup input on add liquidity

---

src/components/Header/MobileOptions.tsx
src/components/Header/index.tsx

Links should express when link to external sources.
Add missing external link icon on navbar "vote"
**Before**
**Now**
1. Open swapr

Add missing external link icon on navbar "vote"

---

src/utils/ui-constants.js

fixes #1363 
Update landing page text referring to the eco bridge.
1. Open swapr

Update landing page text referring to the eco bridge

---

src/constants/index.tsx
src/utils/index.ts
tests/utils/MetamaskNetworkHandler.ts

Fixes #1550 
This updates blockscout explorer URLs to gnosisscan.io 
There is still one place where we use blockscout. We do gasesatimations with blockscout API and there is no equivalent one in Gnosis scan yet that provides Fast / Normal / Slow. I hope its okay to do that later as a seperate PR.
1. Test from transactions page
2. Test by adding Gnosischain network to Metamask.
3. Test in the transaction submitted modal and the 5 second toast that displays.
4. Test the address / transactions within metamask to see if explorer is added properly in metamask.

update explorer to gnosisscan

---

src/pages/Account/TransactionRows/BridgeTransactionRow.tsx
src/pages/Bridge/BridgeTransactionsSummary.tsx
src/utils/index.ts

Add SocketScan
1. Open `Bridge` page
2. Do transaction through `Socket`
3. If transaction is completed, click on `fromChainId`
4. It should redirect user to `https://socketscan.io/`
5. Check it on `Dashboard` as well
NOTE: Socketscan currently only supports search using source transaction hash.

add socketscan to getExplorerLink function

---

src/components/NetworkSwitcher/NetworkSwitcher.preset.ts
src/constants/index.tsx
src/pages/Bridge/index.tsx

- Disables testnets in Bridge form 
- Remove BNB chain in network switcher

hotfix: remove testnets in network switcher and bridge network selector

---

src/services/EcoBridge/Arbitrum/ArbitrumBridge.tsx
src/services/EcoBridge/Connext/Connext.ts
src/services/EcoBridge/EcoBridge.utils.tsx
src/services/EcoBridge/OmniBridge/OmniBridge.ts
src/services/EcoBridge/Socket/SocketBridge.ts
src/services/EcoBridge/Xdai/XdaiBridge.ts

Fixes #1258
Show 3 decimals on bridge box, instead of 2.
1. Go to bridge and input an amount

feature: show three decimals on bridge box

---

src/hooks/usePairVolume24hUSD.ts

This PR fixes the page breaking and showing 24h volume. 
fixes #1577
1. <<Step one>> Open the page `about`
2. <<Step two>> ...

hotfix: Fix pool page from breaking and shows 24h volume on Arbitrum

---

public/locales/en/swap.json
src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.component.tsx
src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.styles.ts
src/pages/Swap/AdvancedSwapMode/Chart/Chart.component.tsx
src/pages/Swap/AdvancedSwapMode/Chart/Chart.styles.tsx
src/pages/Swap/AdvancedSwapMode/Chart/ChartLoader.component.tsx
src/pages/Swap/AdvancedSwapMode/OrderHistory/OrderHistoryTransaction/OrderHistoryTransaction.tsx
src/pages/Swap/AdvancedSwapMode/PairDetails/PairDetails.component.tsx
src/pages/Swap/AdvancedSwapMode/Trade/Trade.component.tsx
src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts
src/services/AdvancedTradingView/usePairDetails.hook.ts
src/utils/index.ts

Fixes #1584
Improvements to advanced trading view.
1. On advanced trading view

fix: improve advanced trading view

---

src/pages/AppBody.tsx

Add max-width to AppBody to fix full-width on pools add/remove liquidity modal
Fixes #1583
**previous**
**fixed**
1. Go to pools
2. Go to pools

Fix: pools create/add/remove modal has incorrect width 

---

src/services/AdvancedTradingView/adapters/advancedTradingView.adapter.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.adapter.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.types.ts
src/services/AdvancedTradingView/adapters/uniswapV3/uniswapV3.adapter.ts
src/services/AdvancedTradingView/adapters/uniswapV3/uniswapV3.types.ts
src/services/AdvancedTradingView/advancedTradingView.types.ts
src/services/AdvancedTradingView/store/advancedTradingView.reducer.ts
src/services/AdvancedTradingView/store/advancedTradingView.selectors.ts
src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts

Resolves #1587.
I detected an issue with our current way of handling data in `Advanced Trading View`. Every 15 seconds, we are reaching out for the latest data in order to populate the page with fresh data.
I've noticed next logical and optimisation issues:
- same part of the state is being updated with same type of data in multiple chunks at the same time
- adapters state in **Advanced Trading View**'s state slice is being reseted every 15 seconds
- we are presenting fetching state in `Trades` component for the background updates
- there is way to differentiate background update calls which get the latest data from the calls which get an older data.
Next is done:
- updated fetching the data methods both for trades and burns & mints
- created **Redux** actions which update the state with …

Optimisation of Data Dispatching to Redux in Advanced Trading View

---

src/services/AdvancedTradingView/adapters/adapters.config.ts
src/services/AdvancedTradingView/adapters/advancedTradingView.adapter.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.adapter.test.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.adapter.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.queries.ts
src/services/AdvancedTradingView/adapters/baseAdapter/base.types.ts
src/services/AdvancedTradingView/adapters/uniswapV3/uniswapV3.adapter.ts
src/services/AdvancedTradingView/adapters/uniswapV3/uniswapV3.queries.ts
src/services/AdvancedTradingView/adapters/uniswapV3/uniswapV3.types.ts
src/services/AdvancedTradingView/advancedTradingView.types.ts
src/services/AdvancedTradingView/store/advancedTradingView.reducer.ts
src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts

Resolves #1586.
After thorough inspection of **Advanced Trading View** mode and updates data dispatching optimization, I've noticed much room for improvement of data fetching. Right now, we are sending at least 10 API calls every 15 seconds reaching out for `swaps`, `burns` and `mints`. Data of each of those calls was dispatched to **Redux** separately, now it is dispatched in two chunks, one for `swaps` and the other for `burns` and `mints`; that part was updated in my previous pull request.
Considering we're using **GraphQL** for data fetching there is more room for optimisation as query language allows requesting of custom data and in that way we can significantly reduce the number of calls and number of actions that are dispatched to **Redux**.
I wrote new fetching queries together …

Optimisation of Data Fetching in Advanced Trading View

---

src/utils/liquidityMining.ts

Fixes #1579
Refactor `getBestApyPairCampaign` function.
- improve variables names
- only return currentCampaign if the APY is greater. 
- added checks to see if campaign did not launch yet
- Add check to see if campaign is already closed.
1. Go to liquidity pools

Fix: carrot pill by refactoring getBestApyPairCampaign

---

src/analytics/fathom/fathom.types.ts
src/pages/Swap/Components/ChartTabs.tsx

Adds necessary hooks to send page view when users hops between simple and advanced trading view

chore: add page views for pro swap

---

bin/fathom-generate-events/eco-bridge-platforms.ts
bin/fathom-generate-events/fathom-generate-events.ts
bin/fathom-generate-events/file-content-generator.ts
bin/tsconfig.json
src/analytics/generated/dev/fathom-events.json
src/analytics/generated/dev/index.ts
src/analytics/generated/prod/fathom-events.json
src/analytics/generated/prod/index.ts
src/analytics/provider/analytics.context.ts
src/analytics/provider/analytics.provider.tsx
src/analytics/provider/analytics.state.ts
src/analytics/trackers/index.ts
src/analytics/utils/index.ts
src/hooks/useSwapCallback.ts
src/pages/Bridge/BridgeTransactionsSummary.tsx

Adds tracking ability to EcoBridge transactions. I think the implementation is a bit hacky; please look at the Transaction Summary component to see the logic. 
The convention for tracking USD volume is as follows:
`<FromChain>/ecoBridge/<BridgeName>/<ToChain>/usdVolume`
Examples:
- `ethereum-1/ecoBridge/socket/arbitrum-42161/volumeUSD`
- `arbitrum-42161/ecoBridge/socket/ethereum-1/volumeUSD`
- `arbitrum-42161/ecoBridge/socket/polygon-137/volumeUSD`
- `polygon-137/ecoBridge/socket/arbitrum-42161/volumeUSD`
[Bridge tx](https://gnosisscan.io/tx/0x73367f4c65e467801eecccb48ed5949b875c99eacae3527862e41cf512d5ce82)

feat: add fathom analytics to ecobridge

---

src/data/Reserves.ts
src/state/mint/reducer.ts

Fixes #1685
This PR fixes the add liquidity bug for new tokens
1. Go to create liquidity page
2. Choose token pair with no liquidity

fix: add liquidity bug

---

src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
src/pages/Swap/LimitOrderBox/constants/index.ts

Fixes #1673
Default limit price to 1%
1. Open limit orders

feature: default limit price to 1%

---

src/components/Modal/index.tsx
src/components/SearchModal/CurrencySearch/CurrencySearch.component.tsx

Resolves #1656.
There's an issue with Currency Searching modal in mobile view, while typing currencies are not visible because they are behind the keyboard. This pull request resolves that by updating base modal stylings in mobile view by moving the modal to the top of the screen. Updated is the logic as well in order to create more functional Currency Searching modal, when you start typing common currencies are removed from the modal.
🍀

Updated Base Modal Styling and Currency Searching Modal Logic

---

src/pages/Swap/LimitOrderBox/components/InputGroup/styled.ts
src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx

This input should only accept numbers. This fixes bug that shows `NAN% `.
1. Go to limit orders

fix:  limit price input type on limit order box

---

src/pages/Swap/LimitOrderBox/api/index.ts
src/pages/Swap/LimitOrderBox/components/ConfirmLimitOrderModal/ConfirmationHeader.tsx
src/pages/Swap/LimitOrderBox/components/ConfirmLimitOrderModal/index.tsx
src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
src/pages/Swap/LimitOrderBox/components/LimitOrderForm/utils.ts
src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/styles.ts
src/pages/Swap/LimitOrderBox/utils/hooks.ts

#1693 
Now limit order `Maximum possible amount ` is showing after reducing the fees. Since the new CoW SDK change we don't want to pass the fees. 
So its a better experience for the users.
API for Cancel an open order has changed in the new SDK and need to make those changes to work.
- Should be able to place a limit order with the maximum available amount
- Should be able to cancel and open limit order.

[#1693] Fix limit order SDK changes

---

src/pages/Bridge/index.tsx
src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormProvider.tsx

This PR fixes a bug where the limit order provider doesn't work well outside unsupported chains
1. Open application in any page while in testnet

fix: limit order unsupported chains bug

---

.github/workflows/ci.yml

The last yarn upgrade missed fixing CI yarn install for synpress and cypress. So it's failing.
In develop branch CI is failing in yarn install.
Created another bug to fix the Cypress failing and fix the multiple yarn install steps. #1708

Fix yarn install in CI

---

src/lib/eco-router/platforms.ts

Show 1inch platform
1. Simulate a trade

fix: show 1inch platform

---

src/hooks/usePairVolume24hUSD.ts

This PR fixes a bug that appears when block by timestamp query is out of sync, by checking if any data is returned.
- Go to liquidity page on arbitrum

fix: unchecked number field when fetching blocks number

---

src/constants/index.tsx

* Added ~$DAI~  $BUSD (per @berteotti request) as default output token for BNB Chain swaps
3) Go to Swapr landing page
4) Connect your wallet and select BNB Chain
5) **$BNB** should be preselected as default **INPUT** token and **$BUSD** should be preselected as default **OUTPUT** token

[1813][FEATURE] - Add $BUSD as default output token for BNB Chain swaps

---

src/constants/index.tsx

* Remove $DXD as a common base swap token from Mainnet, Arbitrum One and Gnosis Chain
3) Go to Swapr landing page
4) Connect your wallet and select any of the following: Mainnet, Arbitrum One or Gnosis Chain
5) **$DXD** should NOT be present in the "Common list" for suggested base tokens on the swap

[SWA-31][FEAT] - Remove $DXD from common base swap tokens

---

src/components/Header/index.tsx

* Temporarily hide the Expeditions pill from the UI
3) Go to Swapr landing page
5) "Expeditions" pill shout NOT appear on the top right

[SWA-27][FEAT] - Temporarily hide the Expeditions pill from the UI

---

src/components/Header/MobileOptions.tsx
src/components/Header/index.tsx

Update the header. Move bridge near Swap.
Add DCA to header
Check if DCA is seen and accessible

[SWA-64] Rearrange header

---

src/constants/index.tsx

This PR removes ARB from common token on mainnet.

fix: remove ARB common token from mainnet

---

src/state/application/hooks.tsx
src/theme/index.tsx

* Update background in Popups to be as intended
3) Go to Swapr landing page
5) All the popups should have their corresponding backgrounds: Liquidity V3 should have the black&purple and the TX popup should have it's dark gray background

[SWA-131][FIX] - Update background in Popups to be as intended

---

src/assets/images/swapr-logo-dark-with-ring.svg
src/state/application/hooks.tsx

* Remove a CSS rule that breaks the Liquidity V3 Popup BG in webkit browsers
3) Go to Swapr dApp page
5) Liquidity V3 BG popup should look normal in desktop and mobile devices, including iOS

[SWA-133][FIX] - Liquidity V3 Popup breaks on iOS

---

src/constants/index.tsx

* Update the pre-selected output currency for Gnosis, to be WETH
3) Go to Swapr dapp page
5) For Gnosis Chain, you should see pre-selected $XDAI (native token) as the input token and $WETH as the output token in the Swapbox

[SWA-141][FEAT] - Change default Gnosis Chain output token to $WETH

---

src/pages/Swap/LimitOrderBox/api/cow.ts

Convert CoW Protocol limit orders to zero-signed fee orders
```
--FROM--
Sell token: A
Sell amount: x
Fee: f
Buy token: B
Buy amount: y
--TO--
Sell token: A
Sell amount: x + f
Fee: 0
Buy token: B
Buy amount: y
```
Related to https://snapshot.org/#/cow.eth/proposal/0xfb81daea9be89f4f1c251d53fd9d1481129b97c6f38caaddc42af7f3ce5a52ec

update: update CoW Swap limit order to zero fee amount

---

src/components/SpaceBg/SpaceBg.tsx

fix: bg image on big screens

---

package.json
yarn.lock

chore: update swapr sdk 1.11.2

---

src/utils/prices.ts

Checks if denominator is 0, preventing a "diving by zero" error.

fix: diving by zero error on limitNumberOfDecimalPlaces

---

src/lib/eco-router/api.ts

Remove price impact filters from trades, this is blocking some tokens who have diff price impact rules, we should probably  do a more robust solution if we want to filter on price impact.

remove price impact filter from ExactIn trades
