SwaprHQ/swapr-dapp

- src/components/CurrencyLogo/index.tsx
- src/pages/AddLiquidity/ProtocolFeeBar.tsx
- src/pages/Pool/index.tsx
- src/state/user/hooks.tsx
> Fix issues 46 47 48 50

- src/hooks/Tokens.ts
- src/pages/Pool/index.tsx
- src/state/user/hooks.tsx
fix #49 
It also uses user added ad bases to check liquidity against.
> fix(pools): Fix to load right pair on pool view refresh

- src/components/PositionCard/index.tsx
- src/pages/App.tsx
- src/pages/Pool/index.tsx
- Move message about how swap fees works to the bottom.
- Change in the ui of the pools view, colors, borders, etc, to match dxswap design.
- Change the margin between the main component and the header, the designs shows less space between main components and header.
> Pool view UI changes

- src/components/Badge/index.tsx
- src/components/Button/index.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/NavigationTabs/index.tsx
- src/components/NumericalInput/index.tsx
- src/components/Popover/index.tsx
- src/components/QuestionHelper/index.tsx
- src/components/SearchModal/CurrencySearch.tsx
- src/components/SearchModal/SortButton.tsx
- src/components/SearchModal/styleds.tsx
- src/components/Tooltip/index.tsx
- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/AdvancedSwapDetailsDropdown.tsx
- src/components/swap/FormattedPriceImpact.tsx
- src/components/swap/SwapModalFooter.tsx
- src/components/swap/SwapRoute.tsx
- src/components/swap/TradePrice.tsx
- src/components/swap/styleds.tsx
- src/constants/index.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/AppBody.tsx
- src/pages/Pool/styleds.tsx
- src/pages/RemoveLiquidity/index.tsx
- src/pages/Swap/index.tsx
- src/theme/index.tsx
Partially implemented swap box and add liquidity box.
PR opened to avoid getting to a point where it is too big to analyze without missing stuff.
Missing things will be implemented in subsequent PRs
> Partially implement new swap and add liquidity box

- src/components/Button/index.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/Header/index.tsx
- src/components/Modal/index.tsx
- src/components/Popover/index.tsx
- src/components/Settings/index.tsx
- src/components/Toggle/index.tsx
- src/components/TransactionSettings/index.tsx
- src/components/Web3Status/index.tsx
- src/pages/AppBody.tsx
- src/state/user/reducer.ts
- src/theme/index.tsx
Updated the navbar in order to align it with Figma designs.
> Review and update navbar

- src/components/Button/index.tsx
- src/components/Card/index.tsx
- src/components/Header/index.tsx
- src/components/NavigationTabs/index.tsx
- src/components/Option/index.tsx
- src/components/PositionCard/index.tsx
- src/components/Slider/index.tsx
- src/components/TransactionSettings/index.tsx
- src/components/earn/styled.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Pool/index.tsx
- src/pages/RemoveLiquidity/index.tsx
- src/state/burn/hooks.ts
- src/state/mint/hooks.ts
- src/state/swap/hooks.ts
Implements the liquidity provisioning view as seen on Figma.
> Liquidity provisioning view

- src/components/Header/MobileOptions.tsx
- src/components/Header/index.tsx
- src/components/Header/styleds.ts
- src/components/Modal/index.tsx
- src/components/SearchModal/styleds.tsx
- src/components/Settings/index.tsx
- src/components/Toggle/index.tsx
In particular:
- Fixed settings menu experience on both desktop and mobile
- Fixed cursor not displaying on toggle, on active toggle
- Fixed governance menu item color on mobile menu
> General bugfixes and polishing

- src/components/SearchModal/styleds.tsx
searchbox - hide placeholder on focus
> searchbox - hide placeholder on focus

- package.json
- src/components/AccountDetails/index.tsx
- src/index.tsx
- src/set-xdai-addresses.ts
- yarn.lock
Dynamically set xDAI router/factory addresses (taken from env) and upgrade the SDK to fetch token from the DXswap token list on xDAI.
> Feature/dynamic xDAI addresses

- src/components/NetworkWarningModal/index.tsx
- src/components/Web3ReactManager/index.tsx
- src/hooks/useTargetedChainIdFromUrl.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Swap/index.tsx
> Multi chain links

- src/state/mint/hooks.ts
The issue shows itself in the following scenario:
Token A is worth 10 times less than token B, and both have 18 decimals (min supported value: 1 wei).
A user tries to add liquidity to the pair token A/token B.
They type in a minuscule amount for token A, in particular `0.000000000000000001` (1 wei). The token B is automatically set to 1 tenth of the amount of token A, which would result in 1/10th of a wei, which makes the app crash (values less than 1 wei are not supported).
> Avoid app crashing when providing minuscule amounts of liquidity

- src/components/Pagination/index.tsx
- src/theme/index.tsx
Simplify pagination and improve it when a lot of pages need to be displayed.
> Simplify pagination

- public/index.html
Fix Twitter previews once and for all.
> Fix Twitter previews

- public/index.html
> Fix: make IPFS-deployed build work

- src/pages/Bridge/index.tsx
> add wallet connector to bridge

- src/components/Pool/LiquidityMiningCampaignView/StakeCard/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/TokenAmountDisplayer/index.tsx
- src/components/Popover/index.tsx
- src/components/Tooltip/index.tsx
> Added tooltips to rewards section

- src/components/Button/index.tsx
- src/components/Pool/PairView/index.tsx
- src/components/PositionCard/index.tsx
- src/pages/Pools/index.tsx
- src/theme/components.tsx
closes #358 
- This is how it looks like on pair page with this pr
> DxStats link on pair page

- src/components/Header/MobileOptions.tsx
> fix pairs&rewards section name is missing on mobile view

- src/components/Web3Status/index.tsx
> fix button text for mobile view

- src/components/LiquidityMiningCampaigns/RewardsList/index.tsx
- src/pages/Pools/LiquidityMiningCampaign/index.tsx
#559 
Addresses this issue by redirecting user to rewards section when they switch network and pair doesn't exist....
> Infinite loading rewards section

- src/hooks/singleSidedStakeCampaigns/useSwaprSingleSidedStakeCampaigns.ts
> Staking Indicator fix

- src/components/NumberBadge/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/Information/index.tsx
- src/pages/Rewards/index.tsx
> Fixes for beta 10

- src/pages/Pools/LiquidityMiningCampaign/index.tsx
What the title suggest. Closes #588
> bugfix: swapr-588 clicking on add liquidity takes user to swap page

- src/components/Header/index.tsx
- src/hooks/singleSidedStakeCampaigns/useSwaprSingleSidedStakeCampaigns.ts
- This issue is caused by subgraph not updating in timely manner so quickfix is to fetch is straight from contrac
- Since rest of data  on rewards section is also from subgraph I think making fixes like this would just make it incosistent
closes #597
> fix: Added hook that fetches data stright from contract

- src/components/Pool/LiquidityMiningCampaignView/TokenAmountDisplayer/index.tsx
- Add 2px margin bottom to reward
- Closes #614
> [Feature] Add margin to reward

- src/components/Header/MobileOptions.tsx
- src/components/Header/index.tsx
closes #594 
@zamli I pushed changes tell me if some more modifications are needed...
> Updated styles for new navigation

- src/components/LiquidityMining/ConfirmStakingRewardsDistributionCreation/StakingRewardsDistributionCreationModalFooter.tsx
- src/components/LiquidityMining/Create/Steps/PreviewAndCreate/PoolSummary/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/Information/index.tsx
> [Fix] Change hour to 24H format

- package.json
- src/connectors/index.ts
- src/constants/index.tsx
- yarn.lock
- Remove authereum connector
- Uninstall web3-react authereum lib
- Closes #600
> [Feature] Remove authereum

- CONTRIBUTING.md
- README.md
Adds a contributing guidelines
> docs: add Contribution Guidelines

- .github/workflows/ci.yml
Adds a CI job which:
- Lints the code
- Runs unit tests
- Bundles a build
> feature: add CI job 

- src/connectors/CustomWalletLinkConnector.ts
- src/hooks/useENSAvatar.ts
- src/react-app-env.d.ts
Fixes linting errors in the code after adding #657
> fix: lint errors

- src/components/LiquidityMiningCampaigns/TabTitle/index.tsx
> [Fix] Add rectangular loader to campaigns tabs

- src/components/Header/index.tsx
- src/components/Header/swpr-info/index.tsx
> [Fix] Add loader to swapr balance

- src/components/LiquidityMining/Create/Steps/PairAndReward/AssetSelector/index.tsx
- src/components/LiquidityMining/Create/Steps/PreviewAndCreate/PoolSummary/index.tsx
- src/components/LiquidityMining/Create/Steps/PreviewAndCreate/RewardSummary/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/Information/index.tsx
- src/components/SearchModal/PairList.tsx
- src/pages/Pools/LiquidityMiningCampaign/index.tsx
- src/pages/Pools/index.tsx
- src/pages/Rewards/index.tsx
- Rename WETH to ETH in rewards page and pairs search
- Closes #608
> [Feature] Change WETH to ETH in rewards page

- src/constants/index.tsx
Added HND, MAI, MR and fixed a bunch of thumbnails that gave a 404.
> added new tokenlist

- src/components/CurrencyInputPanel/index.tsx
- src/components/FiatValueDetails/index.tsx
- src/pages/Swap/index.tsx
- Creates FiaValueDetails component
- Updates balance display and header  on CurrencyInputPanel
> [Feature] Add usd price impact

- src/components/swap/SwapButton.tsx
- src/constants/index.tsx
- src/pages/Swap/index.tsx
- Creates SwapButton
- Creates new routable plataform style constant
- Only gradient available is for Sushiswap at the moment
> [Feature] New swap button

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other.md
- .github/pull_request_template.md
Adds:
- Issues templates:
- Feature Request
- Bug report
- Epic for scoping a number of tickets
- Other (general)
- PR templates
> feature: add GitHub Issues and PR templates

- src/services/Omnibridge/store/Omnibridge.selectors.ts
Closes #727
- available token lists are first filtered by from & to chainId
> fixed token lists

- src/services/Omnibridge/Arbitrum/ArbitrumBridge.tsx
- src/services/Omnibridge/Socket/SocketBridge.ts
Calculate fee in % instead of $
> display fee in percents instead of USD

- src/pages/Swap/index.tsx
- src/state/application/reducer.test.ts
- src/state/multicall/reducer.test.ts
- src/state/multicall/utils.test.ts
- src/state/swap/hooks.test.ts
- src/utils/chunkArray.test.ts
- src/utils/index.test.ts
- src/utils/index.ts
- src/utils/prices.test.ts
- src/utils/prices.ts
- src/utils/uriToHttp.test.ts
- Fixes unit tests
- Skips some unit tests because the function definition and expected return values have changed
> chore: fix tests

- src/services/Omnibridge/Arbitrum/ArbitrumBridge.tsx
Closes #789
When Arbitrum cannot estimate gas -  display `-` in other case display gas in `USD`
> display '-' when Arbitrum Bridge cannot estimate gas

- src/services/Omnibridge/Socket/Socket.utils.ts
- src/services/Omnibridge/Socket/SocketBridge.ts
Closes #798 
If Socket API returns 500 then set status of bridge to failed
> handle Socket API error

- src/constants/index.tsx
Fixes #803 
Check if you are able to see COW token in the token list in Mainnet and Gnosis chain.
> add COW token

- src/components/CurrencyInputPanelBridge/index.tsx
- src/components/CurrencyLogoBridge/index.tsx
- src/pages/Bridge/BridgeModals/BridgeDisclaimerModal.tsx
- src/pages/Bridge/index.tsx
- src/services/Omnibridge/Arbitrum/ArbitrumBridge.tsx
- src/services/Omnibridge/Socket/Socket.lists.ts
- src/services/Omnibridge/Socket/SocketBridge.ts
- src/services/Omnibridge/hooks/Omnibrige.hooks.ts
> add socket whitelisted tokens

- src/connectors/index.ts
- src/constants/index.tsx
Fixes #867
Replaces the current xDAI RPC for gnosis chain RPC
1. <<Step one>> Open the landing page without a wallet connection
> Replace current xDAI RPC for gnosis chain RPC

- .github/workflows/codeql-analysis.yml
- Adds CodeQL analysis tool workflow
> feature: add codeql-analysis.yml

- README.md
- public/index.html
- src/components/Header/MobileOptions.tsx
- src/components/Header/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/Information/index.tsx
- src/components/Pool/PairView/index.tsx
- src/components/PositionCard/index.tsx
- src/components/Settings/index.tsx
- src/components/WalletModal/index.tsx
- src/components/claim/ActionButton/index.tsx
- src/pages/GovPages/index.tsx
- src/pages/Pools/index.tsx
- src/utils/ui-constants.js
- src/utils/uriToHttp.test.ts
- tests/cypress/integration/smoke/MenuBarTests.ts
- tests/cypress/integration/smoke/TransactionSettingsTests.ts
Fixes #899
User gets error 522 when trying to get to dxstats so we are changing all these URLs
1. yarn start
2. open in browser
3. verify links
> 899 - Change relevant eth.link to eth.limo URLs

- src/components/PageWrapper/index.tsx
- src/pages/GovPages/index.tsx
- src/pages/LiquidityMining/Create/index.tsx
- src/pages/LiquidityMining/styleds.ts
- src/pages/Pools/LiquidityMiningCampaign/index.tsx
- src/pages/Pools/Mine/index.tsx
- src/pages/Pools/Pair/index.tsx
- src/pages/Pools/index.tsx
- src/pages/Pools/styleds.tsx
- src/pages/Rewards/index.tsx
Simplify and move page wrapper to it's own component. Make it consistent across usages.
> Add empty state base

- public/locales/en.json
- src/components/Badge/Carrot/index.tsx
- src/components/LiquidityMiningCampaigns/List/index.tsx
- src/components/Pool/LoadingList/LoadingCard/index.tsx
- src/components/Pool/LoadingList/index.tsx
- src/components/Pool/PairsList/Pair/index.tsx
- src/components/Pool/PairsList/index.tsx
Me and @Diogomartf are working on updating the design of liquidity page and also the fonts and colors.
We will do this smaller PRs and merge it on a "main" branch, `feature/fonts-and-colors-liquidity-page`.
--- 
Closes #888
Refactor liquidity page list
> Refactor liquidity page list

- src/pages/Pools/Pair/index.tsx
WIP
Me and @Diogomartf are working on updating the design of liquidity page and also the fonts and colors.
This is work in progress it's not finished, but we want to divide the work in smaller chunks and do things incrementally.
We will do this smaller PRs and merge it on a "main" branch, feature/fonts-and-colors-liquidity-page.
> [Feature] Trade button link on pair detail page

- src/components/Pool/PairView/PoolStats.tsx
- src/components/Pool/PairsList/CampaignCard/index.tsx
Me and @Diogomartf are working on updating the design of liquidity page and also the fonts and colors.
We will do this smaller PRs and merge it on a "main" branch, `feature/fonts-and-colors-liquidity-page`.
---
Add APY value to pair pools stats
> WIP: [Feature] Add pool stats APY value

- src/components/Button/index.tsx
- src/components/Pool/PairView/PoolStats/PoolStats.container.tsx
- src/components/Pool/PairView/PoolStats/PoolStats.types.tsx
- src/components/Pool/PairView/PoolStats/index.tsx
- src/components/Pool/PairView/UserLiquidity/UserLiquidity.container.tsx
- src/components/Pool/PairView/UserLiquidity/UserLiquidity.tsx
- src/components/Pool/PairView/UserLiquidity/index.tsx
- src/pages/Pools/Pair/index.tsx
Me and @berteotti are working on updating the design of liquidity page and also the fonts and colors.
We will do this smaller PRs and merge it on a "main" branch, `feature/fonts-and-colors-liquidity-page`.
---
Organize code with new folder structure.
> Add new folder structure to liquidity details view

- public/locales/en.json
- src/components/Pool/PairsList/PairsList.container.tsx
- src/components/Switch/index.tsx
- src/pages/Pools/index.tsx
Me and @Diogomartf  are working on updating the design of liquidity page and also the fonts and colors.
We will do this smaller PRs and merge it on a "main" branch, `feature/fonts-and-colors-liquidity-page`.
---
Fix styles and add translations in liquidity page
> [Feature] Minor fixes to liquidity page

- src/hooks/useAllLiquidityMiningCampaigns.ts
- src/hooks/usePairLiquidityMiningCampaigns.ts
- src/pages/Pools/Pair/index.tsx
- src/utils/liquidityMining.ts
Refactor usePairLiquidityMiningCampaigns to it's own component
- use getLowerTimeLimit and getTokenAmount
> WIP liquidity: Refactor usePairLiquidityMiningCampaigns to it's own component

- tests/cypress/integration/smoke/LiquidityTests.ts
- tests/cypress/integration/smoke/MenuBarTests.ts
- tests/pages/MenuBar.ts
- tests/pages/NetworkSwitcher.ts
- tests/synpress/specs/networkSwitching/SwitchingNetworkTests.ts
- tests/synpress/specs/swap/SwapTests.ts
Added support for Polygon in tests
> Added tests for Polygon network

- src/theme/index.tsx
Fixes #1077
Loading images in button was missing.
It was due to a dynamic class. Now more classes are added to handle future scenarios
Go to polygon and try swap and see the loading button.
> Fix missing loading logos

- src/lib/eco-router/hooks.ts
> bugfix: Swapr is looking for a route endlessly when wallet is not connected

- src/utils/prices.ts
This was a regression introduced by GPv2 PR
> bugfix: does not show price impact and fee for Uniswap

- public/locales/en-US.json
- public/locales/en.json
- src/components/swap/SwapSettings.tsx
- src/components/swap/TradeDetails.tsx
Enables/activates the MEV Protection badge
> feature: enable MEV protection badge when COW selected

- src/state/application/hooks.tsx
Fixes regression caused by #1155
> bugfix: unplanned change in the style of the transaction notification window

- src/services/EcoBridge/Xdai/XdaiBridge.ts
Added `return` statement inside `getBridingMetadata` method in `xDai Bridge`
> add return statement in getBridgingMetadata

- src/components/Header/Balances.tsx
- src/components/Header/index.tsx
Brings back the unsupported network popover
> bugfix(#1261): show unsupported network popover

- src/components/LandingPageComponents/layout/Footer.js
- src/components/SpaceBg/SpaceBg.tsx
- src/pages/App.tsx
- src/pages/Swap/index.tsx
It is part of the ticket Trades History mostly focus on styling template
> Feature/trades history styling template 

- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.component.tsx
- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.query.ts
- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.styles.ts
- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.types.ts
- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.utils.ts
- src/pages/Swap/AdvancedSwapMode/index.ts
- src/pages/Swap/AdvancedSwapMode/usePair.ts
> fetch trade and liquidity history for selected pair

- public/locales/de/common.json
- public/locales/de/swap.json
- public/locales/en-US/common.json
- public/locales/en-US/swap.json
- public/locales/en/common.json
- public/locales/en/swap.json
- public/locales/es-AR/common.json
- public/locales/es-AR/swap.json
- public/locales/es-US/common.json
- public/locales/es-US/swap.json
- public/locales/it/common.json
- public/locales/it/swap.json
- public/locales/iw/common.json
- public/locales/iw/swap.json
- public/locales/ro/common.json
- public/locales/ro/swap.json
- public/locales/ru/common.json
- public/locales/ru/swap.json
- public/locales/vi/common.json
- public/locales/vi/swap.json
- public/locales/zh-CN/common.json
- public/locales/zh-CN/swap.json
- public/locales/zh-TW/common.json
- public/locales/zh-TW/swap.json
- src/components/swap/SwapButtons/SwapButton.tsx
Fixes swap button message
1. Simulate a trade
> fix: fix swap button messages

- src/services/EcoBridge/Socket/Socket.utils.ts
> socket bridge - additional check for token price

- src/components/swap/Tabs.tsx
- src/pages/Swap/index.tsx
> Set disabled swap tabs for unsupported chains and disable adv trade view

- tests/cypress/integration/smoke/MenuBarTests.ts
- tests/synpress/specs/02transactionfull/bridge/BridgeTests.ts
Skipped tests that will be working after #1379 is fixed
> Skipped failing bridge tests

- public/locales/de/account.json
- public/locales/en-US/account.json
- public/locales/en/account.json
- src/components/Badge/Carrot/index.tsx
- src/components/Badge/SimpleText/index.tsx
- src/pages/Account/Account.styles.tsx
- src/pages/Account/Account.tsx
- src/pages/Account/Account.types.ts
- src/pages/Account/TransactionRows/SwapTransactionRow.tsx
- src/pages/Account/TransactionRows/TransactionHeaders.tsx
- src/pages/Account/accountUtils.ts
- src/ui/StyledElements/PageWrapper.tsx
Fixes #1479
Fix pending transaction sorting
Pending transactions should appear at the top of the list
> Fix pending transaction sorting

- src/constants/index.tsx
- src/state/swap/hooks.ts
Closes #1445 
- Check if the output currency is selected automatically on 
`MAINNET`
`GNOSIS`
`ARBITRUM_ONE`
`POLYGON`
`OPTIMISM`
On testnets output currency should not be automatically selected
> swapbox - preselect outputCurrency

- tests/cypress/integration/smoke/SwapBoxTests.ts
- tests/pages/SwapPage.ts
This pr contains few small fixes for smoke tests
> Fixes for smoke tests

- src/hooks/useAbortController.ts
- src/state/swap/hooks.ts
Fixes #1461
This PR solves the laggy input / trade result on swap page.
> fix: laggy input on swap

- src/components/Header/HeaderButton.tsx
@0xVenky requested change to make Expeditions button look like currency balance button.
> feature(expeditions): redesign expeditions button

- src/components/Routing/RouteCheck.tsx
> fix(routing): fix broken condition

- .gitignore
- package.json
- public/index.html
- src/analytics/provider/analytics.provider.tsx
- src/components/PageMetaData/PageMetaData.tsx
- src/hooks/useEnvironment.ts
- src/pages/Account/Account.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/App.tsx
- src/pages/Bridge/index.tsx
- src/pages/GovPages/index.tsx
- src/pages/LiquidityMining/Create/index.tsx
- src/pages/Pools/LiquidityMiningCampaign/index.tsx
- src/pages/Pools/Pair/index.tsx
- src/pages/Pools/index.tsx
- src/pages/RemoveLiquidity/index.tsx
- src/pages/Rewards/index.tsx
- src/pages/Swap/index.tsx
Add dynamic title and fix fathom in swapr.site
Each page should show a dynamic title in browser title. 
eg:
Fathom should work properly in netlify builds and swapr.site. Should fix the below error
> Add dynamic title and fix fathom in swapr.site

- src/components/Button/Button.tsx
- src/components/Claim/ClaimModal.tsx
Fixes #1322
Disable stake and unstake buttons on swapr details modal
> fix: disable stake and unstake

- .github/workflows/ci.yml
> Fixed label checker in CI

- .gitignore
- .storybook/preview.js
Update storybook preview to add globalstyles and also add storybook-static to gitignore
1. Nothing visible changed. Everything should works as before.
> update storybook preview to use global styles

- src/constants/index.tsx
Add MIVA token to tokenlist. 
Make sure this token is available in Gnosis chain token list.
> Add MIVA token to tokenlist

- src/constants/index.tsx
- src/hooks/Tokens.ts
- src/state/lists/wrapped-token-info.ts
Fixes #1458
Rename ETH to WETH.
> fix: eth to weth on tokenlist

- src/constants/features.ts
- src/pages/Swap/index.tsx
> hotfix: disable charts feature

- src/pages/Swap/AdvancedSwapMode/AdvancedSwapMode.styles.ts
- src/pages/Swap/AdvancedSwapMode/PairDetails/PairDetails.component.tsx
- src/services/AdvancedTradingView/usePairDetails.hook.ts
Improve pair detail UX on advanced trading view
> fix: improve pair detail on advanced trading view

- src/pages/Swap/AdvancedSwapMode/PairDetails/PairDetails.component.tsx
Rename relative price component
> feature: rename relative price component

- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/utils.ts
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/styles.ts
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/pages/Swap/LimitOrderBox/interfaces/order.interface.ts
Adds market price difference in percentage in the limit order price
> feature: add market price diff percentage

- src/services/EcoBridge/store/EcoBridge.selectors.ts
Fixes:
- Omni bridge should be showing once 
- Xdai bridge should be avaliable again as option when bridging xDai/Dai
> Fixed omni bridge showing twice and Xdai bridge not being avaliable

- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/utils.ts
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx
Fixes #1606
Add fixed to 6 decimals and clean bugs (wrong market price when swapping tokens and market price difference with big number)
> fix: add fixed decimals and remove bugs

- src/hooks/usePairVolume24hUSD.ts
<<if there's an issue>>Fixes #issueNumber
*High-level description of what your changes are accomplishing*
*Add screenshots if applicable. Images are nice :)*
1. <<Step one>> Open the page `about`
2. <<Step two>> ...
> Graph query optimization

- src/components/LandingPageComponents/layout/Hero.js
- src/pages/Swap/Swap.tsx
Remove `LandingPage` when in **Swapr** is in pro mode.
Closes #1637.
🍀
> Updated App Layout in Swap Pro Mode

- src/pages/Swap/AdvancedTradingViewBox/AdvancedSwapMode/AdvancedSwapMode.component.tsx
Enable `Open Orders` button and create open orders filtering functionality.
Closes #1639.
🍀
> Open Orders Filtering Functionality

- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/pages/Swap/LimitOrderBox/interfaces/order.interface.ts
- src/pages/Swap/LimitOrderBox/utils/index.ts
Improve limit orders UX. Now it's possible to change any token amount and affect the opposing token amount. Similar to CowSwap.
> feature: improve limit orders UX

- src/services/AdvancedTradingView/adapters/advancedTradingView.adapter.ts
- src/services/AdvancedTradingView/store/advancedTradingView.reducer.ts
- src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts
> bugfix(trading): trade history list empty

- public/locales/en/swap.json
- src/assets/images/progress-circle.svg
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/MarketPriceButton.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/styles.ts
- src/pages/Swap/LimitOrderBox/constants/index.ts
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/theme/index.tsx
Refetch market price every 15 seconds. Changes fetch price logic and market price button UI. Also addresses #1664
> feature: refetch market price

- src/connectors/index.ts
- src/constants/data.ts
- src/constants/index.tsx
- src/hooks/useUSDValue.ts
- src/pages/Account/Account.types.ts
- src/pages/Account/TransactionRows/TransactionRows.tsx
- src/pages/Account/utils/swapTransactionsUtils.ts
- src/pages/Swap/AdvancedTradingViewBox/AdvancedSwapMode/AdvancedSwapMode.component.tsx
- src/pages/Swap/AdvancedTradingViewBox/AdvancedSwapMode/OrderHistory/OrderHistoryTransaction/OrderHistoryTransaction.tsx
- src/pages/Swap/LimitOrderBox/utils/hooks.ts
- src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts
- src/services/AdvancedTradingView/useAllTrades.hook.ts
- src/state/transactions/hooks.tsx
- src/utils/getLibrary.ts
Fixes #1638 
- Add proper currency logo and formatting
> bugfix(#1638): standardize Transactions

- src/pages/Swap/Components/SwapButtons/SwapButtons.tsx
> Buttons text fix

- src/components/CurrencyInputPanel/CurrencyInputPanel.component.tsx
Fixes react fragment error on console.
1. Go to swap page
> fix: react fragment error fix

- src/components/CurrencyInputPanel/CurrencyInputPanel.component.tsx
- src/index.tsx
- src/pages/App.tsx
- src/pages/Pools/Pair/index.tsx
- src/pages/Swap/Components/ChartTabs.tsx
- src/pages/Swap/Components/Tabs.tsx
- src/pages/Swap/LimitOrderBox/components/ConfirmLimitOrderModal/index.tsx
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/components/OrderExpiryField.tsx
- src/pages/Swap/LimitOrderBox/components/OrderLimitPriceField/OrderLimitPriceField.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormProvider.tsx
- src/pages/Swap/LimitOrderBox/utils/index.ts
- src/pages/Swap/Swap.tsx
- src/pages/Swap/SwapBox/SwapBox.component.tsx
- src/pages/Swap/SwapBox/SwapContext.ts
- src/pages/Swap/SwapBox/SwapProvider.tsx
- src/pages/Swap/SwapContext.tsx
- src/services/AdvancedTradingView/useAdvancedTradingView.hook.ts
- src/state/swap/hooks.ts
- src/theme/index.tsx
Fixes #1680
Persist limit order context between tabs and pro mode.
> feature: persist limit order context

- .github/dependabot.yml
- .github/workflows/ci.yml
- src/services/EcoBridge/Socket/api/swagger.json
- src/utils/index.ts
Fixes #1691
Should fix errors in the workflow run
Tests should run without checksum errors
Dependabot should tag correct labels and dev's
CI workflow should run without warnings
> [1691] Update Github workflows

- src/constants/index.tsx
> feature: update token list

- package.json
- src/analytics/trackers/index.ts
- src/hooks/useUSDValue.ts
- src/index.tsx
- src/pages/Swap/LimitOrderBox/components/ConfirmLimitOrderModal/index.tsx
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormProvider.tsx
- src/utils/coingecko.ts
- yarn.lock
This PR improves coingecko API requests performance so there are less errors. Also, this PR fixes native currency price fetching from coingecko API
- Verify that there are no errors when fetching prices in the browser console
- Verify that swapping native currencies trigger fathom events
> fix: coingecko api requests

- .github/pull_request_template.md
- README.md
- package.json
- src/analytics/trackers/index.ts
- src/hooks/usePairVolume24hUSD.ts
- src/hooks/useUSDValue.ts
- src/index.tsx
- src/pages/Swap/AdvancedTradingViewBox/AdvancedSwapMode/Chart/Chart.styles.tsx
- src/pages/Swap/LimitOrderBox/components/ConfirmLimitOrderModal/index.tsx
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormContext.tsx
- src/pages/Swap/LimitOrderBox/contexts/LimitOrderFormProvider.tsx
- src/utils/coingecko.ts
- yarn.lock
Pending milestones on this release.
> release: v1.0.0-beta.19.1

- src/constants/lists.ts
Add Coingecko arbitrum tokens list to the currency list
New tokens should be on the list. eg: ARB
May create wrong swap quotes if dont  liquidity in any dexes
> Add Uniswap tokens to list

- src/components/TransactionConfirmationModal/index.tsx
- src/pages/Bridge/BridgeModal/BridgeModal.styles.ts
- src/pages/Bridge/BridgeModal/BridgeModal.tsx
- src/pages/Bridge/BridgeModal/BridgeModal.types.ts
- src/pages/Bridge/BridgeModal/BridgeModalContent.tsx
Bridge success icon fix
Bridge success icon should not be warning
Low. Icon update
> [#1746] Bridge success icon fix

- src/components/Pool/LiquidityMiningCampaignView/StakeCard/ConfirmStakingModal/index.tsx
- src/components/Pool/LiquidityMiningCampaignView/StakeCard/index.tsx
- src/hooks/useApproveCallback.ts
Fix modal bug on stake card
Try to deposit  and stake on rewards campaign
> fix: fix modal bug on stake card

- src/components/SelectionList/SelectionList.tsx
- src/pages/Bridge/BridgeSelectionWindow.tsx
- src/pages/Swap/Components/SwapPlatformSelector.tsx
- src/services/EcoBridge/Arbitrum/ArbitrumBridge.tsx
- src/services/EcoBridge/Connext/Connext.ts
- src/services/EcoBridge/Lifi/Lifi.utils.ts
- src/services/EcoBridge/Lifi/LifiBridge.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.ts
- src/services/EcoBridge/Socket/Socket.utils.ts
- src/services/EcoBridge/Socket/SocketBridge.ts
- src/services/EcoBridge/Xdai/XdaiBridge.ts
- src/utils/formatNumber.ts
> #1783 Bridge routes decimals fix

- chompfile.toml
https://chompbuild.com/
npm install -g chomp
Then you can run
```
chomp start
chomp serve
chomp build
chomp typecheck 
chomp lint
```
Difference -> Everything faster
> feat: Chomp for faster dev tasks

- src/components/NetworkSwitcherPopover/index.tsx
Fix network loader when there is no account
> fix: network loader

- src/hooks/useApproveCallback.ts
- src/lib/eco-router/platforms.ts
> fix: add velodrome

- bin/fathom-generate-events/eco-bridge-platforms.ts
- src/pages/Bridge/BridgeModal/BridgeModal.tsx
- src/services/EcoBridge/EcoBridge.config.ts
- src/services/EcoBridge/EcoBridge.types.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.adapter.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.config.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.reducers.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.selectors.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.types.ts
- src/services/EcoBridge/OmniBridge/OmniBridge.utils.ts
- src/services/EcoBridge/OmniBridge/abis/abi.ts
- src/services/EcoBridge/OmniBridge/subgraph/history.ts
- src/services/EcoBridge/OmniBridge/subgraph/tokens.ts
- src/services/EcoBridge/store/EcoBridge.reducer.ts
- src/services/EcoBridge/store/EcoBridge.selectors.ts
Reverts ImpeccableHQ/swapr-dapp#1800
> Revert "fix: remove omnibridge"

- src/utils/uiConstants.tsx
> fix: update discord link

- public/index.html
- src/components/expeditions/ExpeditionsModal.tsx
- src/utils/uiConstants.tsx
Updating our twitter URL from @SwaprETH to @Swapr_dapp
> fix: update twitter URL

- package.json
- yarn.lock
> chore: update swapr sdk 1.9.2

- src/pages/Swap/Components/SwapPlatformSelector.tsx
Improve price impact info on eco router.
> feat: improve price impact info

- src/pages/Pools/RemoveLiquidity/index.tsx
Smart Contract accounts seem to not deal well with off-chain approvals. This fixes remove liquidity by doing the approval on-chain
> fix: allow smart contract to remove liquidity

- src/lib/eco-router/api.ts
- src/pages/Swap/Components/SwapPlatformSelector.tsx
- src/pages/Swap/Components/SwapPlatformSelectorLoader.tsx
Give a better and cleaner experience on eco router
> feat: improve eco router experience

- src/connectors/index.ts
Move infura key to env so it's easy to update it
> fix: move infura key to env

- src/connectors/index.ts
- src/hooks/useGasInfo.ts
Removes infura dependency so we don't have more failing requests
> fix: remove infura dependency

- src/pages/App.tsx
This PR adds an URL warning banner.
> feat[SWA-130]: add URL warning banner

- public/locales/en/common.json
- src/components/Header/index.tsx
- src/components/Popups/LiquidityV3Popup.tsx
- src/constants/urls.ts
Updates liquidity V3 link to the new URL.
> chore: update liquidity V3 link

- src/apollo/client.ts
- src/constants/lists.ts
* Rectify Swapr subgraph comments
* Update failing token list URLs
3) Go to Swapr dapp page
5) Go to the Swapbox, select a token, click on "Manage token list" and scroll down, all relevant token lists for the selected chain should be available and no fetch error should be present.
> [SWA-143][IMPROVEMENT] - Update failing token list URLs

- src/analytics/fathom/fathom.types.ts
- src/analytics/hooks/useSimpleAnalyticsEvent.ts
- src/analytics/trackers/index.ts
* Update the FA tracking implementation due to the new API
3) Go to Swapr dapp page
5) Go to the Swapbox, make any trade using SwaprV3, and sign it. That trade should be displayed in FA Dashboard for the corresponding site
> [SWA-144][IMPROVEMENT] - Add SwaprV3 traded volume FA tracking

- package.json
- src/components/SpaceBg/SpaceBg.tsx
- src/pages/Swap/LimitOrderBox/api/cow.ts
- yarn.lock
- update CoW swap to zero fee amount
- fix bg image on big screens
- update swapr sdk 1.11.2
- new version 1.0.0-beta.22.1
> release: 1.0.0-beta.22.1

- src/components/Header/index.tsx
- src/pages/App.tsx
- src/pages/Pools/index.tsx
- Update the header to include swapr.eth.link
- Remove the liquidity banner
- Move Pools V2 to header so that we stop all the requests coming to Discord and scammers lurking.
> Few small changes due

- package.json
- src/pages/Swap/LimitOrderBox/api/cow.ts
- src/pages/Swap/LimitOrderBox/components/LimitOrderForm/LimitOrderForm.tsx
- src/state/transactions/updater.tsx
- tsconfig.json
- yarn.lock
* Updates our `yarn.lock` file to get the CoW SDK new version
* Updates our CoW SDK tools typing
* Updates our `yarn start` command removing the socket codegen script.
> [STK-123][CHORE] -Update CoW typing to remove errors
